backend:
  name: bitbucket
  repo: smddev/site-netlify # Path to your Bitbucket repository
media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site
media_library:
  name: cloudinary
  config:
    cloud_name: 'smddev'
    api_key: '451488314613789'

collections:
  - name: "industry"
    label: "Industry"
    folder: "src/content/industries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", default: 0, min: 0}
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string", required: false}

  - name: "service"
    label: "Service"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", default: 0, min: 0}
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string", required: false}

  - name: "tech"
    label: "Technologies"
    folder: "src/content/techs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", default: 0, min: 0}
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Code", name: "code", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}

  - name: "member"
    label: "Members"
    folder: "src/content/members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", default: 0, min: 0}
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "project"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", default: 0, min: 0}
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Industries"
        name: "industries"
        widget: "list"
        field:
          - label: "Industry"
            name: "industry"
            widget: "relation"
            collection: "industry"
            searchFields: ["title"]
            displayFields: ["title"]
            valueField: "id"
      - label: "Services"
        name: "services"
        widget: "list"
        field:
          - label: "Service"
            name: "service"
            widget: "relation"
            collection: "service"
            searchFields: ["title"]
            displayFields: ["title"]
            valueField: "id"
      - label: "Technologies"
        name: "techs"
        widget: "list"
        field:
          - label: "Technology"
            name: "tech"
            widget: "relation"
            collection: "tech"
            searchFields: ["title"]
            displayFields: ["title"]
            valueField: "id"
      - label: "Members"
        name: "members"
        widget: "list"
        field:
          - label: "Member"
            name: "member"
            widget: "relation"
            collection: "member"
            searchFields: ["title"]
            displayFields: ["title"]
            valueField: "id"

  - name: "post"
    label: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "member"
        searchFields: ["title"]
        displayFields: ["title"]
        valueField: "id"

