backend:
  name: bitbucket
  repo: smddev/site-netlify # Path to your Bitbucket repository
media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site
media_library:
  name: cloudinary
  config:
    cloud_name: 'smddev'
    api_key: '451488314613789'
    output_filename_only: true

collections:
  - name: "industry"
    label: "Industry"
    folder: "src/content/industries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string", required: false}

  - name: "service"
    label: "Service"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string", required: false}

  - name: "tech"
    label: "Technologies"
    folder: "src/content/techs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Code", name: "code", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}

  - name: "member"
    label: "Members"
    folder: "src/content/members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "project"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", default: 0, min: 0}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Industries"
        name: "industries"
        widget: "list"
        field:
          - {label: "Industry", name: "industry", widget: "string"}
      - label: "Services"
        name: "services"
        widget: "list"
        field:
          - {label: "Service", name: "service", widget: "string"}
      - label: "Technologies"
        name: "techs"
        widget: "list"
        field:
          - {label: "Technology", name: "tech", widget: "string"}
      - label: "Members"
        name: "members"
        widget: "list"
        field:
          - {label: "Member", name: "member", widget: "string"}

  - name: "post"
    label: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string", required: false}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "index"
        file: "src/content/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Portfolio"
        name: "portfolio"
        file: "src/content/portfolio.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About"
        name: "about"
        file: "src/content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contacts"
        name: "contacts"
        file: "src/content/contacts.md"
        fields:
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
