backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "industry"
    label: "Industry"
    folder: "src/content/industries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}

  - name: "project"
    label: "Project"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Industries"
        name: "industries"
        widget: "list"
        field:
          - label: "Industry"
            name: "author"
            widget: "relation"
            collection: "industry"
            searchFields: ["name"]
            valueField: "name"
            displayFields: ["name"]

  - name: "post"
    label: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

